conversion_task:
  description:
    Before starting any process first convert the given pdf files in data/CVs directory into md files 
    using the convert_pdf_to_md function in main.py file then store the converted files into same location


read_job_description_task:
  description: >
    Extract relevant information from the given job description. Focus on skills, experience,
    education, and key achievements.
    Ensure to capture  summary, technical skills,
    work history, and educational background.


    md file: {path_to_jobs_md}
  expected_output: >
    A structured summary of the job_description, including:
    -Key Features
    

match_candidate_task:
  description: >
    
    Given job description match the best fit candidate from the Ashish_tandon.md,
    Guru_sharan.md,
    Vikas Resume (1).md,
    VInayPvvsr (1).md, 
    Viviek_chabra.md,   files
    Evaluate how well the candidate's profiles fit with the job description from Jobs md file,
    focusing on the alignment of skills, work history, and key achievements
    with the job requirements.


    Jobs md file: {path_to_jobs_md}

    Ashish_tandon.md: {path_to_cv_0}
    Guru_sharan.md: {path_to_cv_1}
    Vikas Resume (1).md: {path_to_cv_2}
    VInayPvvsr (1).md: {path_to_cv_3}
    Viviek_chabra.md: {path_to_cv_4}

  expected_output: >
    A ranked list of top 3 candidates that best match the job description, including:
    - Name of candidate
    - Match Score (based on skills and experience)
    - Key Matching Points
