read_job_description_task:
  description: >
    Extract relevant information from the given job description. Focus on skills, experience,
    education, and key achievements.
    Ensure to capture  summary, technical skills,
    work history, and educational background.


    CSV file: {path_to_jobs_csv}
  expected_output: >
    A structured summary of the job_description, including:
    -Key Features
    

match_candidate_task:
  description: >
    Given job description match the best fit candidate from the cv.md,cv2.md,cv3.md,cv4.md,cv5.md  files
    Evaluate how well the candidate's profiles fit with the job description from Jobs CSV file,
    focusing on the alignment of skills, work history, and key achievements
    with the job requirements.


    Jobs CSV file: {path_to_jobs_csv}

    cv.md: {path_to_cv}
    cv2.md: {path_to_cv2}
    cv3.md: {path_to_cv3}
    cv4.md: {path_to_cv4}
    cv5.md: {path_to_cv5}

  expected_output: >
    A ranked list of top 3 candidates that best match the job description, including:
    - Name of candidate
    - Match Score (based on skills and experience)
    - Key Matching Points
